from __future__ import annotations

from typing import Any, Dict


DEFAULT_LAMMPS_TEMPLATE = """# Auto-generated by AgentsMD-compatible template processor
units metal
dimension 3
boundary p p p
atom_style atomic

variable initTemp equal {initial_temp}
variable targetTemp equal {target_temp}
variable runSteps equal {run_steps}
variable boxSize equal {box_size}

{structure_setup}

pair_style {pair_style}
pair_coeff {pair_coeff}

neighbor 2.0 bin
neigh_modify delay 10 check yes
timestep {time_step}
velocity all create {velocity_temp} 4928459 mom yes rot yes dist gaussian
thermo 100
thermo_style custom step temp pe ke etotal press
dump 1 all custom {dump_interval} {dump_file} {dump_fields}
{dump_modify_line}
{fix_line}
run {run_steps}
"""


class LammpsTemplateProcessor:
    def __init__(self, template_text: str | None = None) -> None:
        self.template_text = template_text or DEFAULT_LAMMPS_TEMPLATE

    def get_form_schema(self) -> Dict[str, Any]:
        return {
            "title": "单金属 LAMMPS 模拟配置",
            "type": "layered_form",
            "submit_label": "生成脚本并运行",
            "sections": [
                {
                    "title": "1. 基础模型设置",
                    "description": "定义材料、晶胞尺寸和初始温度",
                    "fields": [
                        {
                            "key": "material",
                            "label": "材料",
                            "default": "Cu",
                            "type": "string",
                            "component": "select",
                            "options": ["Al", "Cu", "Ni"],
                            "desc": "当前 demo 支持的单金属材料",
                        },
                        {
                            "key": "box_size",
                            "label": "晶胞重复数",
                            "default": 4,
                            "type": "number",
                            "component": "input",
                            "unit": "lattices",
                            "desc": "定义模拟盒尺寸，例如 4 代表 4x4x4",
                        },
                        {
                            "key": "initial_temp",
                            "label": "初始温度",
                            "default": 300,
                            "type": "number",
                            "component": "input",
                            "unit": "K",
                            "desc": "速度初始化和加热起始温度",
                        },
                    ],
                },
                {
                    "title": "2. 任务与时间参数",
                    "description": "控制任务类型、目标温度和步数",
                    "fields": [
                        {
                            "key": "task_type",
                            "label": "任务类型",
                            "default": "equilibration",
                            "type": "string",
                            "component": "select",
                            "options": ["equilibration", "heating"],
                            "desc": "平衡或升温任务",
                        },
                        {
                            "key": "target_temp",
                            "label": "目标温度",
                            "default": 900,
                            "type": "number",
                            "component": "input",
                            "unit": "K",
                            "desc": "equilibration 时会作为恒温值，heating 时会作为升温终点",
                        },
                        {
                            "key": "run_steps",
                            "label": "运行步数",
                            "default": 5000,
                            "type": "number",
                            "component": "input",
                            "unit": "steps",
                            "desc": "LAMMPS `run` 的步数",
                        },
                        {
                            "key": "time_step",
                            "label": "时间步长",
                            "default": 0.001,
                            "type": "number",
                            "component": "input",
                            "unit": "ps",
                            "desc": "积分时间步长",
                        },
                    ],
                },
                {
                    "title": "3. 势函数与系综",
                    "description": "选择势函数族、系综和输出设置",
                    "fields": [
                        {
                            "key": "potential_family",
                            "label": "势函数类型",
                            "default": "eam",
                            "type": "string",
                            "component": "select",
                            "options": ["eam", "lj"],
                            "desc": "金属任务通常使用 EAM",
                        },
                        {
                            "key": "ensemble",
                            "label": "模拟系综",
                            "default": "NVT",
                            "type": "string",
                            "component": "select",
                            "options": ["NVT", "NPT"],
                            "desc": "NPT 适合允许体积变化的平衡阶段",
                        },
                        {
                            "key": "dump_file",
                            "label": "轨迹文件名",
                            "default": "dump.atom",
                            "type": "string",
                            "component": "input",
                            "desc": "LAMMPS dump 输出文件名",
                        },
                    ],
                },
            ],
        }

    def render(self, config: Dict[str, Any]) -> str:
        required_fields = (
            "initial_temp",
            "target_temp",
            "run_steps",
            "box_size",
            "structure_setup",
            "pair_style",
            "pair_coeff",
            "time_step",
            "velocity_temp",
            "dump_interval",
            "dump_file",
            "dump_fields",
            "dump_modify_line",
            "fix_line",
        )
        missing = [field for field in required_fields if field not in config]
        if missing:
            raise ValueError(f"Missing template fields: {', '.join(missing)}")
        return self.template_text.format(**config)
